name: medicai

volumes:
  uploads-data:
  db-data:

networks:
  db-net:
  web-net:

services:
  app:
    image: ghcr.io/dalbitresb12/medicai-backend:latest
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      STATIC_DIRECTORY: '/mnt/static'
      UPLOADS_DIRECTORY: '/mnt/uploads'
    volumes:
      - uploads-data:/mnt/uploads:rw
      - ./static:/mnt/static:ro
    networks:
      db-net:
        aliases:
          - app.medicai.internal
  web:
    image: ghcr.io/dalbitresb12/medicai-frontend:latest
    build:
      context: ./frontend
    expose:
      - "8080"
    networks:
      web-net:
        aliases:
          - web.medicai.internal
  db:
    image: mysql:8
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 10s
      start_interval: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE:-medicai}'
      MYSQL_USER: '${MYSQL_USER:-medicai}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-}'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db-data:/var/lib/mysql:rw
    networks:
      db-net:
        aliases:
          - db.medicai.internal
